# Generated by Django 3.1.7 on 2021-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='Electronics'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='1'),
        ),
    ]
